FROM python:3.12.8-alpine

# Set the working directory
WORKDIR /app

# Install necessary packages using apk
RUN apk update && apk add --no-cache \
    wget \
    unzip

# Download and install Terraform
RUN wget --quiet https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_arm64.zip \
  && unzip terraform_1.10.5_linux_arm64.zip \
  && mv terraform /usr/bin \
  && rm terraform_1.10.5_linux_arm64.zip


  CMD ["python", "-m", "http.server", "8000"]